#!/bin/sh
export TERM=xterm-256color

echo $(tput setaf 2)
figlet username @ hostname

upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

# get the load averages
read one five fifteen rest < /proc/loadavg

echo "$(tput setaf 3)
 `date +"%A, %e %B %Y, %r"`
 `uname -srmo`$(tput setaf 6)
 Uptime.............: ${UPTIME}
 Running Processes..: `ps ax | wc -l | tr -d " "`
 IP Addresses.......: `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/` and `wget -q -O - http://icanhazip.com/ | tail`
$(tput sgr0)"


